### ISSUE TITLE
Suggested improvements to Flights Widget

### ISSUE THREAD

**Issue by gjhaynes** [offer-shmuely/edgetx-x10-widgets#1]
Thank you for the work you have done to create the EdgeTX Widgets. The Flights Widget is very useful.
I would like to suggest some improvements to the Flights widget.

1. Add the option to set the text color to make it more compatible with different color themes
2. Add detection of "TRSS" to verify telemetry. This allows the widget to work with more receivers. e.g. Spektrum

I also noticed that I cannot disable the sounds from the options. I was able to fix this problem by changing
_if (wgt.options.enable_sounds) then_
to
_if (wgt.options.enable_sounds == 1) then_

Regards,
Geoff

**Comment by offer-shmuely** [comment]
Hi
Thanks for your suggestions 
#1 already implemented 
#2 I will add it

sounds: the option removed to free a space for the color option ( #1)
You can however delete the sound file instead)

**Comment by offer-shmuely** [comment]
* option to set the text color - implemented 
* added TRSS to telemetry indication

**Comment by gjhaynes** [comment]
That's great! Thanks for doing this so quickly.
