### ISSUE TITLE
Flights - set switch position

### ISSUE THREAD

**Issue by rufus-se** [offer-shmuely/edgetx-x10-widgets#10]
Hi.
I really like the flights widget. I have several switches that would be suitable for the widget but it seems like all of them turn the widget of instead of on. I would like to use something like my kill switch or timer switch instead of setting up another switch just for this widget. I'm sure I will forget to either start or stop it then. 
It would be great if one could set switch position to turn the widget. Nothing fancy just be able to select if it is SA↑. SA- or SA↓ that turns the widget on.

**Comment by offer-shmuely** [comment]
I tried, but the current API does not support it.
maybe they will update the api in the future, so I will do it.
currently, your best option, is to create a logical-switch (that can be set in the widget), and define there what  you like

**Comment by rufus-se** [comment]
Ok, sounds like a good explanation. Keep my fingers crossed for an API update then :-) 
Would be great to be able to use the 6P buttons, as well as !.

**Comment by offer-shmuely** [comment]
Hi
please check the following enhancement (ver 0.9)

I can not do it on the GUI configuration, but you know can set in in the widget script

on the /flights/main.lua
under configuration (line: 68)

I added inverted_switch_logic
0=armed when SF up
1=armed when SF down (my default)
