### ISSUE TITLE
GaugeRotary Widget disappears after reading / writing a model in EdgeTX Companion

### ISSUE THREAD

**Issue by BompaBert** [offer-shmuely/edgetx-x10-widgets#13]
EdgeTX companion version 2.9.2.                SD Structure path destination is an exact copy of the X10S SD Card.
Frsky X10S Express EdgeTX version 2.9.2
The GaugeRotary Widget disappears from the Main View 1 on all models after using EdgeTX companion to write models and settings to radio.
Attached screenshots (view and setup) from before reading into Companion. An 1 screenshot after writing. 
![after](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/152647971/d8917413-8e85-41b7-9f12-32274c2f7faf)
![before](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/152647971/cec3e64c-bfd9-4918-918f-e79694ab2333)
![setup](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/152647971/7d491a06-ab4c-4e66-b72d-a4ec5f6ddd8c)

**Comment by offer-shmuely** [comment]
Yes, I saw it recently, 
From some reason the companion can handle less characters in the name, than the firmware it self.
One option will be to change the name, but many user already use it.
A better way, will be to open a bug on the main repo, to fix the companion

**Comment by BompaBert** [comment]
Indeed, removing 1 char, GaugeRotar instead of GaugeRotary, in the Widget name and replacing the same in the main.lua file made the Widget appear again in all my models. All set.

**Comment by offer-shmuely** [comment]
Open a bug for companion on the main edgetx/edgetx repo

**Comment by BompaBert** [comment]
Done.
X10 widgets -- GaugeRotary disappears from radio model setup after reading
/ writing a model in Companion #4528
