### ISSUE TITLE
Flights does not work if no telemetry

### ISSUE THREAD

**Issue by teradactyal** [offer-shmuely/edgetx-x10-widgets#14]
Hi

I fly with Spektrum receivers and some of them don't send any telemetry, it would be nice to have an option to turn off the telemetry requirement to count a flight and just go off the minimum flight time and arm switch.

Thanks

Stephen

**Comment by offer-shmuely** [comment]
use version 1.1
edit the main.lua of the widget
and set line 69 to 0

![image](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/7026911/1edac3d5-9e25-41a0-9406-3d2236b4aa48)

**Comment by teradactyal** [comment]
That solution works if you have all models without telemetry, I just added a telemetry option to the widget setup screen and change the variable based on that.

**Comment by offer-shmuely** [comment]
cool
the current edgeTx api allow only 5 options, 
I will enhance it when this limitation will be enhanced (you can ask it again on the frorms)
