### ISSUE TITLE
Add inverted_arm_switch_logic flag into options of widget

### ISSUE THREAD

**Issue by roscor61** [offer-shmuely/edgetx-x10-widgets#15]
This is an enhancement request, not ad issue. 

i have tried to insert the variable "inverted_arm_switch_logic" as an option:

 options = {
    { "switch", SOURCE, DEFAULT_ARM_SWITCH_ID },
    { "switch_dn_armed", VALUE, inverted_arm_switch_logic, 0, 1 },
    { "motor_channel", SOURCE, DEFAULT_MOTOR_CHANNEL_ID },
    { "min_flight_duration", VALUE, default_flight_starting_duration, 2, 120 },
....

But I have a problem to update the value. 
Unfortunately I know my limits and I can't make it work.
Is it possible to add this as an option and not replace 0 or 1 in the local variable in the lua script?
Thanks in advance

**Comment by offer-shmuely** [comment]
yes, now that I removed the "debug" there is a place for additional field
many complain about it, so lets add it

**Comment by offer-shmuely** [comment]
done, you can try it

**Comment by roscor61** [comment]
Hi,

now it's full functionally!
I have notes your modified code and I have learned some thing.
Thank you!
Vert nice widget


Rosario

Il gio 23 mag 2024, 21:57 Offer Shmuely ***@***.***> ha
scritto:

**Comment by offer-shmuely** [comment]
Cool
Happy to hear you are enjoying it
