### ISSUE TITLE
Value2: Handling of connection states

### ISSUE THREAD

**Issue by karstendf** [offer-shmuely/edgetx-x10-widgets#17]
My setup:
- EdgeTX 2.10.1
- Radiomaster TX16S
- ELRS

The 'Value2' widget currently in non-fullscreen mode shows all values grayed-out, while there is no connection to a receiver. 
('Value2' behavior is different in fullscreen mode, where it displays values also if not connected)
Also it does not display actual numbers while not connected. This is different to the behavior of the built-in widget 'Value', which shows non-telemetry items also when not connected. When using both 'Value2' and 'Value' widgets combined, it would be nice if both would follow the same scheme for switching displays. See attached screenshots (from the RM TX16S) for examples. The screenshots also show that 'Value2' seems not to evaluate the stick mode - I'm using mode 2, and 'Value2' still shows the right gimbal as 'rudder'.

![not connected neutral](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/30924485/f61ba77a-893c-4593-b257-66e3fb204861)
![not connected rudder](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/30924485/e392ac3f-2826-4006-8ad9-c689206d5cc8)
![connected ail](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/30924485/5fe4d903-72e2-4810-97de-019dafa27a6c)
![connected rudder ail](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/30924485/999d2422-19d2-49f3-a020-bbf01d404404)

**Comment by pfeerick** [comment]
> The screenshots also show that 'Value2' seems not to evaluate the stick mode - I'm using mode 2, and 'Value2' still shows the right gimbal as 'rudder'.

Do you sticks have the right names in the inputs or even hardware settings? As I would have though that is where the name was from :thinking:

**Comment by karstendf** [comment]
> Do you sticks have the right names in the inputs or even hardware settings? As I would have though that is where the name was from 🤔<

Actually that was a user error.. I'm not using names in the HW settings, but I did define input names. My setup for the pictures in the original report inadvertently used different sources for the 'Value' (Axis) and the 'Value2' (Inputs) representations. When both use 'Axis', they both show the same signal, however in different units:

![connected rudder rudder](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/30924485/11db5728-0c54-4196-9dac-d50354f2c090)
'Value' uses %, while 'Value2' uses PPM us obviously. Not sure if this is due to some setting on my side (using companion, in the Radio Settings, I have set PPM units to microseconds. On the transmitter itself however, the option 'us' does not exist for PPM units - maybe this causes some confusion somewhere?).

Anyway, if I could make the world to my liking, I'd prefer 'Value2' to
- mimic the behavior of 'Value' regarding the representation of connection states
- also show the small symbols which indicate the type of inputs
- have it use % values for 'Axis' and 'Inputs' (I understand that such a change may cause issues with existing users and may not be acceptable therefore).

**Comment by offer-shmuely** [comment]
Thank you for putting the time to report.
first l like to correct the terminology, when the telemetry is not connected, the value is gray, and you see the last value.
it definitely does not relevant for non telemetry sensors, like the "Rud" 

let me think, what can be done here...

**Comment by karstendf** [comment]
thank you!

**Comment by offer-shmuely** [comment]
[Value2.zip](https://github.com/user-attachments/files/15843068/Value2.zip)
try this version, it may be better.

for the 100%, I need to find a way to know what field to do the calculation,
did not found one yet

**Comment by karstendf** [comment]
great - coloring of values now works as expected :-)

before connection:
![new_before](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/30924485/65ccfc4b-5a1b-48aa-a9a8-62bb2bd4f426)

while connected:
![new_connected](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/30924485/0a79f273-230e-43ab-9ac9-3ce55e700404)
(the MBat decimal places are not shown for some reason)

disconnected again:
![new_after](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/30924485/55a6b3dc-b857-4aab-9183-90996738be4f)

**Comment by offer-shmuely** [comment]
for the decimal point, please send a picture of the definition of the MBat on the sensor page

what is the meaning of "disconnected again"?

**Comment by karstendf** [comment]
on 'disconnected again':
this just refers to my test sequence:
- I took the 1st screenshot with the receiver turned off, i.e. no telemetry connection
- the 2nd screenshot shows the state after turning on the receiver, i.e. with telemetry
- for the 3rd screenshot, the receiver was switched off again, i.e. telemetry lost

Here's the definition of the MBat sensor (had to take two screenshots for the full information):
![MBat definition I](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/30924485/fc3aec25-428f-4a00-a588-7b4da0e032c5)
![MBat definition II](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/30924485/2c24c152-2d28-4a22-91db-c06b3849212b)
The loss of the decimal place in 'Value2' also appears with other telemetry sensors.

best regards -
Karsten

**Comment by offer-shmuely** [comment]
so I understand that the telemetry is ok.
and here is a fix for the precision bug
[Value2.zip](https://github.com/user-attachments/files/15855581/Value2.zip)

**Comment by karstendf** [comment]
perfect - that did the trick. So once the debug output (load: x%) is turned off, I'd be happy to use it.

(the other two comments I made in [this post](https://github.com/offer-shmuely/edgetx-x10-widgets/issues/17#issuecomment-2167794509) are of low priority and importance to me. 
However I'd second [issue 16](https://github.com/offer-shmuely/edgetx-x10-widgets/issues/16).)
