### ISSUE TITLE
Telemetry Widget GaugeRotary shows disconnected

### ISSUE THREAD

**Issue by G3Dmaker** [offer-shmuely/edgetx-x10-widgets#19]
Radiomaster TX16S 4in1
EdgeTX 2.10.3
RX GR16 HOTT
GaugeRotary show me always disconnected. The telemetry data is coming. AnalogBatt works correctly.
What could be the reason?
Thanks 
Thomas

![screen-2024-08-20-220451](https://github.com/user-attachments/assets/ab23e482-a183-4ed1-bf4a-cf5ad8ffe88a)

**Comment by offer-shmuely** [comment]
can you send a picture of all the telemetry sensor page?
and also a picture of settings of the widget

**Comment by G3Dmaker** [comment]
Here are the screenshots.
Thanks for your help.
![Tele_1](https://github.com/user-attachments/assets/73078221-871f-4ffb-a058-cd2cf7f9a39f)
![Tele_2](https://github.com/user-attachments/assets/42f8d38b-2ed7-4236-89cf-eb122bfbb4cb)
![Widget](https://github.com/user-attachments/assets/b5973858-ff1a-4873-8651-757422d594c3)

**Comment by G3Dmaker** [comment]
AnalogBatt 2s LiPo
![screen-2024-08-25-114221](https://github.com/user-attachments/assets/0664916a-8dd9-4655-b871-f228356bc84e)
![Widget_AnalogBatt](https://github.com/user-attachments/assets/f3e9b60f-cdd4-4720-b477-4483879f3f54)

**Comment by offer-shmuely** [comment]
that is interesting
let try to debug it.
I uploaded to the git ver 9
please download it, and in the file lib_log.lua change line line 4 ENABLE_LOG_TO_FILE to be true instead of false

local ENABLE_LOG_TO_FILE=true

the run it, and send be back the log file "app.log"

**Comment by G3Dmaker** [comment]
here is the file
[app.log](https://github.com/user-attachments/files/16792322/app.log)

**Comment by offer-shmuely** [comment]
I can see something strange 
please try this test version 
[GaugeRotary-0.9-test1.zip](https://github.com/user-attachments/files/16795948/GaugeRotary-0.9-test1.zip)

**Comment by G3Dmaker** [comment]
The strange characters in the log file are gone.
But it is still disconnected.
Here is the new log file: "0.9-test1"
[app.log](https://github.com/user-attachments/files/16803530/app.log)
I am available for further tests.
Thank you

**Comment by G3Dmaker** [comment]
I don't know if it will help you.
In main.lua. 
I have deleted or commented out all ‘wgt.tools.isTelemetryAvailable()’.
In principle it works now. But min and max volts are missing.
![screen-2024-08-30-091448](https://github.com/user-attachments/assets/c703cabc-c808-4828-8a3a-3de0f5f209bc)

**Comment by offer-shmuely** [comment]
Interesting
Did you change manually the names of the sensors?
What RF protocol do you use? elrs?

it looks like you do not have any of this

![image](https://github.com/user-attachments/assets/c3f80373-f20a-4a62-b4bb-c4f4b56cd01f)

**Comment by G3Dmaker** [comment]
Radiomaster TX16S **4in1** **not elrs**
EdgeTX 2.10.3
RX GR16 **HOTT** this is protocol #57 (Graupner HOTT) [https://www.multi-module.org/using-the-module/protocol-details/hott#details](url)
The telemetry screenshots above are standard after a discover new. Without an additional connected telemetry module.
No manual changes made.
This is the same for all of my Graupner HOTT receivers. GR12, GR16 ... GR32
Rbt = Receiver Batt Voltage.
there are also min or max available.
![screen-2024-08-31-130339](https://github.com/user-attachments/assets/8ee7322e-858f-4984-8604-72597125f01b)
On Companion:
![ksnip_20240831-130917](https://github.com/user-attachments/assets/5e9218b4-ba20-4065-b7a5-fc20fe284046)

**Comment by offer-shmuely** [comment]
Ok, now I think I understand.
I never heard of anyone using this protocol, are you from german?
I will add some support for that telemetry detection as well

**Comment by offer-shmuely** [comment]
try this version

[GaugeRotary-0.9-test2.zip](https://github.com/user-attachments/files/16824815/GaugeRotary-0.9-test2.zip)

**Comment by G3Dmaker** [comment]
I am from Switzerland. Graupner HOTT is also present there. But mostly with the original transmitter. I have several model aircraft with Graupner receivers. I switched from Graupner to OpenTX and now to EdgeTX.

GaugeRotary-0.9-test2 works perfectly.
Many many thanks

**Comment by offer-shmuely** [comment]
Nice to hear, both on Switzerland, as well as that it work.
Use this version for now.
I will test it for a while, and PR to the main edgeTx git
