### ISSUE TITLE
batt analog does not work in li-ion setting

### ISSUE THREAD

**Issue by DG9BFC** [offer-shmuely/edgetx-x10-widgets#2]
I tried your Batt analog ... but switching to li-ion shows a fault :-(

ERROR in refresh(): ?:0 attempt to compare number with tabl

switch back to lipo then restart shows the tx battery again
so seems to be a fault in the table??
i just copied your main lua inside the transmitter ... or did i make a fault there?

**Comment by offer-shmuely** [comment]
What was the other settings you put on the widget

**Comment by offer-shmuely** [comment]
ok, found it and fixed the error

**Comment by DG9BFC** [comment]
in li_ion setting and widget to fullscreen the first digit (before decimal) is missing
(prints .1 insted 4.1V in fullscreen ... or .2v instead 8.2v)

**Comment by DG9BFC** [comment]
cause 8.2 shows 100% the voltage value is pushed to the left ... so that explains missing digit :-)
i only see changes on first digit (8.2, 8.1, 8.0) or coarse steps from 100% to 89% to 84%
not 8.12, 8.11, 8.10, 8.09 (but that is what the sensor in battery calibration shows)
means you DISPLAY 2 digits but you do not MEASURE 2 digits
above values would give 4.06, 4.055, 4.05, 4.045 single cell voltage (just some examples) 
in lipo table you even have three digits behind decimal in some values but that can not work if you only use a single digit to measure the packs voltage
measure two digits ... then divide by cell number (in tx battery divide by 2)...take that value (with at best three digits) and compare THAT to your table(s)
that way we have a fine resolution ... be it in volt or in percent steps
now it "jumps" from 100 to 89 to 84%
greetings sigi dg9bfc

**Comment by offer-shmuely** [comment]
full screen updated
![image](https://user-images.githubusercontent.com/7026911/188005093-3944c622-3ca8-414b-9f3a-060380337782.png)

**Comment by offer-shmuely** [comment]
the value internally is not kept in 1 or digit precession, this is only a presentation issue.
we still need to work to the percent conversion table, but for now I put any voltage above 4,1 as full battery, since of the Li0Ion battery can be charge to 4.1v per cell, and some can be charge to 4.2v
i.e. 
* 4.10 == 100%
* 4.15 == 100%
* 4.18 == 100%
* 4.20 == 100%

**Comment by DG9BFC** [comment]
i see the voltage drops in 100mv steps (8.1, 8.0, 7.9) in your widget
that is 100mv steps (or after divide by cell number it is 50mv steps)
but if i look in the hardware calibration window it drops in 10mv steps
and if divide by cell number it is then 5mv steps
THAT is first we need to solve before we can finetune the table ... not?!?
all above say 4.1 to call 100% is ok
call 3v as 0% is also ok
but you need to measure and calculate in finer resolution and then look in the table
al least that is what i would think ... not?!?

**Comment by DG9BFC** [comment]
let me drop in you last change in my transmitter to test :-)
wait a minute

**Comment by DG9BFC** [comment]
100% ... and then after a bit of use
89% (8.0v)
80% (7.9v)
76% (7.8v)
(and so on)
that is what i see here cause you do not use all digits the sensor gives 
.....................
but the new screen layout in fullscreen looks nice :-) .. so thumbs up on that
![IMG_20220901_230734_BURST005](https://user-images.githubusercontent.com/17382592/188014417-f366c33b-13d9-4b85-a02a-19cef017fcd9.jpg)

**Comment by DG9BFC** [comment]
in the battery calibration i see the voltage drop slowly in fine steps
7.81, 7.80, 7.79 etc ....
but not in your widget ...
but that fine resolution is needed cause the voltage drop over the state of charge is so low

**Comment by offer-shmuely** [comment]
it is not the widget that reduce the resolution, it is the c++ api of the main firmware
you need to ask for a change there
this function: 
local v = getValue(wgt.options.Sensor)

you can see this log:
log(wgt.options.source_name .. ", value: " .. fieldinfo.name .. "=" .. v)
