### ISSUE TITLE
The gauge rotary lua errors on main.lua 148; attemp to perform aritmethic on local value (a table value)

### ISSUE THREAD

**Issue by GenuineFlollie** [offer-shmuely/edgetx-x10-widgets#3]
Add the widget to a screen
Select cells as the source
Leave the defaults.
errors when the telemetry is having a value (like 11.5)

This happens on a RadioMaster 16s, but only if I use FrSky VFAS as telemetry source.

**Comment by offer-shmuely** [comment]
Will check it

**Comment by offer-shmuely** [comment]
updated with support for cells sensors

**Comment by GenuineFlollie** [comment]
Thanks, it works now! I am not sure about how to setup the min/max. It seems to be whole digits only, which is not the granularity you would want in a bandwith from 14.8 to 16.8 volt.

**Comment by offer-shmuely** [comment]
yep, that is currently limitation of the API
I will search a solution for that
