### ISSUE TITLE
Version without telemetry

### ISSUE THREAD

**Issue by vladacr** [offer-shmuely/edgetx-x10-widgets#4]
Hi, I really like your Flights widget. I've switched to TX16s an EdgeTX only recently from Futaba. I have quite a lot of Futaba receivers, but the TX16's multi module can use those only without telemetry.

Thus I was wonderring if your widget could alternativelly work without telemetry. The flight could be ended with a throttle kill switch, perhaps?

Thanks for your answer.
Vlad

**Comment by offer-shmuely** [comment]
please try this version
you will need to change in line 49
local use_telemetry = 0

[main.lua.txt](https://github.com/offer-shmuely/edgetx-x10-widgets/files/10127963/main.lua.txt)

**Comment by offer-shmuely** [comment]
any news?

**Comment by offer-shmuely** [comment]
so I assume it is all good

**Comment by vladacr** [comment]
Hello,

I'm sorry for not answering. Yes, everything works perfectly. Thank
you very much.

Regards
Vlad
