### ISSUE TITLE
Voltage symbol not correct after "cosmetic Changes"

### ISSUE THREAD

**Issue by GRacing69** [offer-shmuely/edgetx-x10-widgets#6]
Hello

First of all let me congratulate for the outstanding widgets you have created :) !
After updating your widgets, the Voltage symbol disappeared from the "rotary gauge" widget!
It can be my problem, but i just updated the widgets!
If i have to modify anything please tell me!

Check photos for what is happening (Running Edge Tx 2.8.4 on a Jumper T16 Pro
 
![1685467903091](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/60347948/3348e4b7-79bb-4e9d-b9ac-0cfaa4679245)
![1685467903098](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/60347948/9dff1f61-8105-4272-ad35-5d41cb7cc107)

Best Regards

**Comment by offer-shmuely** [comment]
I can see it, 
the "Cels" telemetry entry have not unit defined
workaround it,
please try the new version V:0.8

**Comment by GRacing69** [comment]
Now it shows!

If i remove the battery the "V" symbol disapears, but when connected all ok now!

Thank you for your help!
![1685643239428](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/60347948/4268ff5d-25c5-4fd9-bd79-8286d137a42b)

**Comment by offer-shmuely** [comment]
cool!
I note you like widget, but does not using the "flights" count.....
try it
