### ISSUE TITLE
Aspd "Airspeed Sensor" not working in Rotary Gauge

### ISSUE THREAD

**Issue by GRacing69** [offer-shmuely/edgetx-x10-widgets#7]
Hello Shmuely!

It´s me again...
 The Aspd sensor isn't recognized by the rotary gauge!
The sensor is connected to INAV, and i don't know if the ID devices are different, but while the normal "value" widget is correctly displayed with the rotary gauge, it doesn't display any value neither the units!

Could you help me/us !?

![1685643239507](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/60347948/79c84ed1-3337-47d6-ba3a-3f0127512517)
![1685643239435](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/60347948/05039fa4-7414-4455-a69d-b44ba9c1b66c)
![1685643239443](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/60347948/0b146083-60e5-41ef-a18d-78e4ef06df5a)
![1685643239443](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/60347948/0b146083-60e5-41ef-a18d-78e4ef06df5a)
![1685643239450](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/60347948/cbf89352-398e-493c-9fe2-d27ff29e9e57)
![1685643239524](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/60347948/e4d945bb-a7c6-43eb-b8d9-446ca149e3ba)

**Comment by offer-shmuely** [comment]
can you try to define the min & max on the widget settings?

**Comment by GRacing69** [comment]
Yes, i already tried, but the result was the same.
Do you think that the ID's of the sensor could be causing this?
In INAV the Aspd sensor is 251, but in Frsky sport protocol the ID is 226....

![1685655471279](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/60347948/4606bcae-aa22-470e-9242-bcdd36222c2b)

**Comment by offer-shmuely** [comment]
Can you send me here a picture of the edit screen of the sensor you use
