### ISSUE TITLE
Test Issue from Jams 

### ISSUE THREAD

**Issue by modefour** [offer-shmuely/edgetx-x10-widgets#8]
![image](https://github.com/offer-shmuely/edgetx-x10-widgets/assets/136178913/153e2543-dd23-4a00-b908-4d76f4c3e940)

That is supped to be a screen snip of the google sheet.

**Comment by modefour** [comment]
looks like the snip comes after the post. 

I will look at this a bit more, but we must remember, most members of the group do are not very IT literate.  Me included.

**Comment by offer-shmuely** [comment]
nice try
I added some tags

**Comment by offer-shmuely** [comment]
now lets add a version as a tag

**Comment by offer-shmuely** [comment]
and close it as it was fix....
